version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/docs"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/src"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for Pip
  - package-ecosystem: "pip"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/src"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: ".github/workflows"
    # Check for updates once a week
    schedule:
      interval: "weekly"
